### ISSUE TITLE
Capture is broken

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/ixnetwork#278]
```python
"""
Configure a raw TCP flow with,
- tx port as source to rx port as destination
- frame count 10000, each of size 128 bytes
- transmit rate of 1000 packets per second
Validate,
- frames transmitted and received for configured flow is as expected
"""
import snappi
# when using ixnetwork extension, host is IxNetwork API Server
api = snappi.api(host='https://localhost:443', ext='ixnetwork')
# new config
config = api.config()
# when using ixnetwork extension, port location is chassis-ip;card-id;port-id
tx, rx = (
    config.ports
    .port(name='tx', location='localhost;1;1')
    .port(name='rx', location='localhost;1;2')
)
# configure layer 1 properties
ly, = config.layer1.layer1(name='ly')
ly.port_names = [tx.name, rx.name]
ly.speed = ly.SPEED_10_GBPS
ly.media = ly.FIBER
# configure capture
cap, = config.captures.capture(name='cap')
cap.port_names = [rx.name]
cap.format = cap.PCAP
# configure flow properties
flw, = config.flows.flow(name='flw')
# flow endpoints
flw.tx_rx.port.tx_name = tx.name
flw.tx_rx.port.rx_name = rx.name
# configure rate, size, frame count
flw.size.fixed = 128
flw.rate.pps = 1000
flw.duration.fixed_packets.packets = 10000
# configure protocol headers with defaults fields
flw.packet.ethernet().vlan().ipv4().tcp()
# push configuration
api.set_config(config)
# start capture
cs = api.capture_state()
cs.state = cs.START
api.set_capture_state(cs)
# start transmitting configured flows
ts = api.transmit_state()
ts.state = ts.START
api.set_transmit_state(ts)
# create a query for flow metrics
req = api.metrics_request()
req.flow.flow_names = [flw.name]
# wait for flow metrics to be as expected
while True:
    res = api.get_metrics(req)
    if all([m.frames_tx == 10000 == m.frames_rx for m in res.flow_metrics]):
        break
```

Traceback
```
Traceback (most recent call last):
  File "test_capture.py", line 50, in <module>
    api.set_transmit_state(ts)
  File "/home/ashukuma/workspace/otg/ixnetwork/snappi_ixnetwork/ixnetworkapi.py", line 190, in set_transmit_state
    self.traffic_item.transmit(payload)
  File "/home/ashukuma/workspace/otg/ixnetwork/snappi_ixnetwork/trafficitem.py", line 543, in transmit
    self._api.capture._start_capture()
  File "/home/ashukuma/workspace/otg/ixnetwork/snappi_ixnetwork/capture.py", line 203, in _start_capture
    self._api._ixnetwork.StartCapture()
  File "/home/ashukuma/workspace/otg/ixnetwork/snappi_ixnetwork/timer.py", line 17, in __exit__
    self._api.info(self._msg + ' %.3fs' % (time.time() - self._start))
AttributeError: 'Capture' object has no attribute 'info'
```

**Comment by ashutshkumr** [comment]
fixed per `snappi[ixnetwork]==0.3.12`
